FROM chainer-base:3.4.0-gpu-py3

#FIXME: cupy/core/core.cpp:41:20: fatal error: Python.h: No such file or directory
RUN apt-get install -y python3.5-dev

RUN pip3 install --no-cache \
     numpy==1.14.0 requests==2.18.4 boto3==1.5.2 \
     six==1.11.0 gevent==1.2.2 gunicorn==19.7.1 flask==0.11 Jinja2==2.9 \
     filelock==3.0.4 protobuf==3.5.1 Pillow==5.0.0 cupy==2.5.0 \
     chainer==3.4.0 chainermn==1.2.0 mpi4py==3.0.0 chainercv==0.8.0 matplotlib==2.2.0

# Edit matplotlibrc to use "Agg" backend by default to write plots to file.
RUN sed -i s/TkAgg/Agg/ /usr/local/lib/python3.5/dist-packages/matplotlib/mpl-data/matplotlibrc

COPY sagemaker-container-support/dist/sagemaker_container_support-1.0-py2.py3-none-any.whl /sagemaker_container_support-1.0-py2.py3-none-any.whl
COPY dist/sagemaker_chainer_container-1.0-py2.py3-none-any.whl /sagemaker_chainer_container-1.0-py2.py3-none-any.whl

RUN pip3 install /sagemaker_container_support-1.0-py2.py3-none-any.whl && pip3 install /sagemaker_chainer_container-1.0-py2.py3-none-any.whl

RUN rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python

ENTRYPOINT ["python", "-m", "chainer_framework.start"]
